export type ModelType = 'modelValue' | string

export type FormComponentType =
  | 'el-input'
  | 'el-input-number'
  | 'el-select'
  | 'el-select-v2'
  | 'el-cascader'
  | 'el-tree-select'
  | 'el-radio-group'
  | 'el-checkbox-group'
  | 'el-switch'
  | 'el-rate'
  | 'el-color-picker'
  | 'el-slider'
  | 'el-divider'
  | 'el-tabs'
  | 'upload-file'
  | 'date'
  | 'daterange'
  | 'textarea'
  | 'table'
  | 'batch-input'
  | 'text'
  | 'options'
